# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\pysocks-feedstock\recipe, last modified Wed Feb 15 01:53:09 2023
# ------------------------------------------------

package:
  name: pysocks
  version: 1.7.1
source:
  sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
  url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
  number: '0'
  script: c:\ci_311\pysocks_1676425991111\_h_env\python.exe -m pip install . --no-deps
    -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
    - win_inet_pton
test:
  imports:
    - socks
about:
  dev_url: https://github.com/Anorov/PySocks
  doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
  home: https://github.com/Anorov/PySocks
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
    more information.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
