# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_9cmlsrm3ys\clone\recipe, last modified Wed Oct 25 19:12:53 2023
# ------------------------------------------------

package:
  name: urllib3
  version: 1.26.18
source:
  sha256: f8ecc1bba5667413457c529ab955bf8c67b45db799d159066261719e328580a0
  url: https://pypi.io/packages/source/u/urllib3/urllib3-1.26.18.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_9cmlsrm3ys\\croot\\urllib3_1698257595508\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.11 h2bbff1b_2
    - pip 23.3 py311haa95532_0
    - python 3.11.5 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - brotli-python >=1.0.9
    - certifi
    - cryptography >=1.3.4
    - idna >=2.0.0
    - pyopenssl >=0.14
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.contrib._securetransport
    - urllib3.packages
    - urllib3.packages.backports
    - urllib3.util
  requires:
    - pip
about:
  description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
    of the

    Python ecosystem already uses urllib3. urllib3 brings many critical features

    that are missing from the Python standard libraries, such as thread safety,

    connection pooling, client side ssl/tls verification, support for gzip and

    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

    and dealing with HTTP redirects.

    '
  dev_url: https://github.com/urllib3/urllib3
  doc_url: https://urllib3.readthedocs.io/
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9c2510fa-dc5c-4d1f-83ac-539a7606470c
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - sethmlarson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/urllib3-feedstock.git
  sha: bb7da29904a51434e491bc5b83e5cc7f7e154e9d
