# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# C:\b\abs_316c2inijk\clone\recipe, last modified Wed Jul 26 20:37:45 2023
# ------------------------------------------------

package:
  name: requests
  version: 2.31.0
source:
  sha256: 942c5a758f98d790eaed1a29cb6eefc7ffb0d1cf7af05c3d2791656dbd6ad1e1
  url: https://pypi.io/packages/source/r/requests/requests-2.31.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_316c2inijk\\croot\\requests_1690400295842\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.9 h2bbff1b_0
    - pip 23.2.1 py311haa95532_0
    - python 3.11.4 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.11,<3.12.0a0
    - urllib3 >=1.21.1,<2
  run_constrained:
    - chardet >=3.0.2,<6
    - pysocks >=1.5.6, !=1.5.7
test:
  commands:
    - pip check
    - conda create -v --dry-run -n requests-test numpy
  imports:
    - requests
  requires:
    - conda
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io/
  home: https://requests.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 316da52d-55ba-4d10-865b-0aa6d52ecc98
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/requests-feedstock.git
  sha: 94562ba40660819756e2e6efd33fcd807fdb4f96
