# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_924gv1kxzj\clone\recipe, last modified Fri Nov 17 20:52:13 2023
# ------------------------------------------------

package:
  name: cffi
  version: 1.16.0
source:
  patches:
    - 0001-Link-to-dl-library.patch
  sha256: bcb3ef43e58665bbda2fb198698fcae6776483e0c4a631aa5647806c25e02cc0
  url: https://pypi.io/packages/source/c/cffi/cffi-1.16.0.tar.gz
build:
  missing_dso_whitelist: null
  number: '0'
  script: C:\\b\\abs_924gv1kxzj\\croot\\cffi_1700254355075\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py311h2bbff1b_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3 py311haa95532_0
    - python 3.11.5 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - pycparser
    - python >=3.11,<3.12.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - python -X faulthandler -c "from cffi import FFI; print(FFI().dlopen('ucrtbase'))"
  imports:
    - _cffi_backend
    - cffi
  requires:
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://github.com/python-cffi/cffi
  doc_url: https://cffi.readthedocs.io
  home: https://cffi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 92e19bfe-30fd-4bab-9582-4b1dadaf8c0b
  recipe-maintainers:
    - goanpeca
    - inducer
    - mingwandroid
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cffi-feedstock.git
  sha: a67629a8551df9b044fae6680720f9d58a0e2c69
