# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_28t5mcoltc\clone\recipe, last modified Fri Sep  1 14:33:20 2023
# ------------------------------------------------

package:
  name: packaging
  version: '23.1'
source:
  sha256: a392980d2b6cffa644431898be54b0045151319d1e7ec34f0cfed48767dd334f
  url: https://pypi.io/packages/source/p/packaging/packaging-23.1.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_28t5mcoltc\\croot\\packaging_1693575224052\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - flit-core 3.8.0 py311haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.10 h2bbff1b_2
    - pip 23.2.1 py311haa95532_0
    - python 3.11.4 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  description: 'Reusable core utilities for various Python Packaging interoperability
    specifications.

    This library provides utilities that implement the interoperability specifications

    which have clearly one correct behaviour (eg: PEP 440) or benefit greatly from
    having

    a single shared implementation (eg: PEP 425).

    '
  dev_url: https://github.com/pypa/packaging
  doc_url: https://packaging.pypa.io
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 28584628-54d3-43bb-b8c6-ec251a26121d
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/packaging-feedstock.git
  sha: a9a65efd919f7a8fb409a5fe0d51ee1169c2178f
