# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_f76j9hg7pv\clone\recipe, last modified Thu Mar 23 09:57:38 2023
# ------------------------------------------------

package:
  name: tqdm
  version: 4.65.0
source:
  sha256: 1871fb68a86b8fb3b59ca4cdd3dcccbc7e6d613eeed31f4c332531977b89beb5
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.65.0.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  number: '0'
  script: C:\\b\\abs_f76j9hg7pv\\croot\\tqdm_1679561871187\\_h_env\\python.exe -m
    pip install . --no-deps -vv
  string: py311h746a85d_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - flit-core 3.8.0 py311haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - packaging 23.0 py311haa95532_0
    - pip 23.0.1 py311haa95532_0
    - python 3.11.0 h966fe2a_3
    - setuptools 65.6.3 py311haa95532_0
    - setuptools-scm 7.0.4 py311haa95532_0
    - setuptools_scm 7.0.4 hd3eb1b0_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 2.0.1 py311haa95532_0
    - typing-extensions 4.4.0 py311haa95532_0
    - typing_extensions 4.4.0 py311haa95532_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - colorama
    - python >=3.11,<3.12.0a0
  run_constrained:
    - ipywidgets >=6
    - requests
    - slack-sdk
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg 4.65.0
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - dask
    - keras
    - numpy
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
    - rich
    - ripgrep
  source_files:
    - pyproject.toml
    - setup.cfg
    - tests
about:
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f7293c63-0808-48ac-a10a-50a7638f59bd
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/tqdm-feedstock.git
  sha: 3d3ee38916b11f0d4cf0ce967b3f6544784cd600
