# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\pluggy-feedstock\recipe, last modified Wed Feb 15 00:49:36 2023
# ------------------------------------------------

package:
  name: pluggy
  version: 1.0.0
source:
  fn: pluggy-1.0.0.tar.gz
  sha256: 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.0.0.tar.gz
build:
  number: '1'
  script: python -m pip install . --no-deps --ignore-installed
  string: py311haa95532_1
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - packaging 22.0 py311haa95532_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_1
    - setuptools 65.5.0 py311haa95532_0
    - setuptools-scm 7.0.4 py311haa95532_0
    - setuptools_scm 7.0.4 haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tomli 2.0.1 py311haa95532_0
    - typing-extensions 4.4.0 py311haa95532_0
    - typing_extensions 4.4.0 py311haa95532_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
test:
  command:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io/en/latest/
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
