#!/bin/sh
_CONDA_ROOT="C:\Users\legio\OneDrive\Desktop\roop\unleashed\roop-unleashed-main\installer\installer_files\conda"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\echo >&2 "DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'."
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda deactivate
