# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_91u83siphd\clone\recipe, last modified Mon Nov 20 17:34:57 2023
# ------------------------------------------------

package:
  name: certifi
  version: 2023.11.17
source:
  - folder: certifi
    sha256: 9b469f3a900bf28dc19b8cfbf8019bf47f7fdd1a65a1d4ffb98fc14166beb4d1
    url: https://pypi.io/packages/source/c/certifi/certifi-2023.11.17.tar.gz
  - folder: pip_wheel
    sha256: 7ccf472345f20d35bdc9d1841ff5f313260c2c33fe417f48c30ac46cccabf5be
    url: https://pypi.io/packages/py3/p/pip/pip-23.2.1-py3-none-any.whl
  - folder: setuptools_wheel
    sha256: b454a35605876da60632df1a60f736524eb73cc47bbc9f3f1ef1b644de74fd2a
    url: https://pypi.io/packages/py3/s/setuptools/setuptools-68.2.2-py3-none-any.whl
build:
  number: '0'
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - python 3.11.5 he1021f5_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
  imports:
    - certifi
  requires:
    - pip
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  home: https://certifi.io/
  license: MPL-2.0
  license_family: Other
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9156d3d9-13f1-4722-80a8-fe428b9d9d2a
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/certifi-feedstock.git
  sha: 3b962b681a8d011c60c2454c35eb3920d887a1c8
  skip-lints:
    - missing_python_build_tool
