# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# C:\b\abs_b9wp3lr1gn\clone\recipe, last modified Wed Aug  2 21:37:52 2023
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.2.0
source:
  sha256: dae0c697cf8757d997d0d7f4fbe48a5516cb17f16b3715dadb6008ade8ef850e
  url: https://github.com/conda/conda-package-handling/archive/2.2.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  number: '0'
  script: C:\\b\\abs_b9wp3lr1gn\\croot\\conda-package-handling_1691008700066\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py311haa95532_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.9 h2bbff1b_0
    - python 3.11.4 he1021f5_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.9 h2bbff1b_0
    - pip 23.2.1 py311haa95532_0
    - python 3.11.4 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - conda-package-streaming >=0.9.0
    - python >=3.11,<3.12.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - mock
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
  source_files:
    - tests
about:
  description: '`conda` and `conda-build` use `conda_package_handling.api` to create
    and extract

    conda packages. This package also provides the `cph` command line tool to

    extract, create, and convert between formats.

    '
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create and extract conda packages of various formats.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b9aee082-05df-4c39-9000-25ba4e42e6a5
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
  remote_url: git@github.com:AnacondaRecipes/conda-package-handling-feedstock.git
  sha: 7fd399ee868576468d4f5e71979445a1f31468ca
