# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_e8cnom_zw_\clone\recipe, last modified Fri Dec  8 21:37:45 2023
# ------------------------------------------------

package:
  name: cryptography
  version: 41.0.7
source:
  sha256: 13f93ce9bea8016c253b34afc6bd6a75993e5c40672ed5405a9c832f0d4a00bc
  url: https://pypi.io/packages/source/c/cryptography/cryptography-41.0.7.tar.gz
build:
  number: '0'
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%
    - C:\\b\\abs_e8cnom_zw_\\croot\\cryptography_1702071486468\\_h_env\\python.exe
      -m pip install . -vv --no-deps --no-build-isolation
  string: py311h89fc84f_0
requirements:
  build:
    - rust 1.71.1 haa95532_0
    - rust_win-64 1.71.1 hd77b12b_0
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - cffi 1.15.1 py311h2bbff1b_3
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3.1 py311haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.11.5 he1021f5_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 68.0.0 py311haa95532_0
    - setuptools-rust 1.5.2 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - typing_extensions 4.7.1 py311haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py311haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cffi >=1.12
    - openssl >=3.0.12,<4.0a0
    - python >=3.11,<3.12.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - pytest -n auto
  requires:
    - cryptography-vectors 41.0.7.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-cov
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/en/41.0.7/
  home: https://github.com/pyca/cryptography
  license: (BSD-3-Clause OR Apache-2.0) AND PSF-2.0 AND MIT
  license_family: BSD
  license_url: https://github.com/pyca/cryptography/blob/41.0.7/vectors/LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e826abe6-5e4b-4bcf-8ce9-956f237bb464
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 007e6f4308502ee56b8394d1471a3edf8a42454b
