# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# C:\b\abs_b6z_yqw_ii\clone\recipe, last modified Wed Aug 16 18:04:16 2023
# ------------------------------------------------

package:
  name: platformdirs
  version: 3.10.0
source:
  sha256: b45696dab2d7cc691a3226759c0d3b00c47c8b6e293d96f6436f733303f77f6d
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-3.10.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_b6z_yqw_ii\\croot\\platformdirs_1692205479426\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - editables 0.3 py311haa95532_0
    - hatch-vcs 0.3.0 py311haa95532_0
    - hatchling 1.18.0 py311haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.10 h2bbff1b_0
    - packaging 23.0 py311haa95532_0
    - pathspec 0.10.3 py311haa95532_0
    - pip 23.2.1 py311haa95532_0
    - pluggy 1.0.0 py311haa95532_1
    - python 3.11.4 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - setuptools-scm 7.1.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - trove-classifiers 2023.3.9 py311haa95532_0
    - typing-extensions 4.7.1 py311haa95532_0
    - typing_extensions 4.7.1 py311haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
    - pytest tests -vv
  imports:
    - platformdirs
  requires:
    - appdirs
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'About A small Python module for determining appropriate

    platform-specific dirs, e.g. a "user data dir".

    '
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b6a19ec7-e4ac-455f-b35d-348e88a01040
  recipe-maintainers:
    - adament
    - gaborbernat
  remote_url: git@github.com:AnacondaRecipes/platformdirs-feedstock.git
  sha: 523c5fef6185e3a10e97e3dc20a33e58b92fd824
