# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_8boqq9524g\clone\recipe, last modified Wed Apr 12 14:01:53 2023
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.5
source:
  sha256: 98e9c3d949d1b924e28e01eccb7deed865eefebf25c2f21c702e5cd5b63b85e1
  url: https://github.com/facebook/zstd/archive/v1.5.5.tar.gz
build:
  number: '0'
  run_exports:
    - zstd >=1.5.5,<1.6.0a0
  string: hd43e919_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - cmake-no-system 3.25.3 h6c2663c_0
    - libffi 3.4.2 hd77b12b_6
    - msinttypes r26 2
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1t h2bbff1b_0
    - python 3.11.2 h966fe2a_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  host:
    - lz4-c 1.9.4 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - lz4-c >=1.9.4,<1.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - xz >=5.2.10,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - zstd -be -i5
    - if not exist %LIBRARY_INC%\zstd.h exit 1
    - if not exist %LIBRARY_BIN%\libzstd.dll exit 1
    - if not exist %LIBRARY_LIB%\libzstd.lib exit 1
    - if not exist %LIBRARY_LIB%\libzstd_static.lib exit 1
  requires: null
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: https://facebook.github.io/zstd/
  license: BSD-3-Clause AND GPL-2.0-or-later
  license_family: BSD
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8bf7c02d-6965-44e1-8b9a-6b8a5807945f
  recipe-maintainers:
    - chenghlee
    - msarahan
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstd-feedstock.git
  sha: c98aad1b99d9c69517f099a4fc51e6d38d7b35ee
