# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_e3bcpyv7sw\clone\recipe, last modified Thu Aug 31 15:03:51 2023
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.2.0
source:
  fn: conda-content-trust-0.2.0.tar.gz
  sha256: ded769f69a0491bd1e002ce949a332ae5a47a60ce733adb8a724802c8fdfe02b
  url: https://github.com/conda/conda-content-trust/archive/0.2.0.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '0'
  script: C:\\b\\abs_e3bcpyv7sw\\croot\\conda-content-trust_1693490654398\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - editables 0.3 py311haa95532_0
    - hatch-vcs 0.3.0 py311haa95532_0
    - hatchling 1.18.0 py311haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.10 h2bbff1b_2
    - packaging 23.0 py311haa95532_0
    - pathspec 0.10.3 py311haa95532_0
    - pip 23.2.1 py311haa95532_0
    - pluggy 1.0.0 py311haa95532_1
    - python 3.11.4 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - setuptools-scm 7.1.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - trove-classifiers 2023.3.9 py311haa95532_0
    - typing-extensions 4.7.1 py311haa95532_0
    - typing_extensions 4.7.1 py311haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cryptography >=41
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
    - conda-content-trust --help
  imports:
    - conda_content_trust
    - conda_content_trust.authentication
    - conda_content_trust.common
    - conda_content_trust.root_signing
    - conda_content_trust.signing
  requires:
    - pip
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e384bc20-39f3-46fb-a0ea-614f5cd97bf0
  remote_url: git@github.com:AnacondaRecipes/conda-content-trust-feedstock.git
  sha: 9e0697695ab43dbcf15c7f406e5f9f2e2a209551
