# This file created by conda-build 3.27.0
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.8.0
source:
  sha256: fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16
  url: https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz
build:
  number: 0
  run_exports:
    - yaml-cpp >=0.8.0,<0.9.0a0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.5.0 hd77b12b_0
    - libffi 3.4.4 hd77b12b_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 3.0.11 h2bbff1b_2
    - python 3.12.0 h1d929f7_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1
    - test/test.bat
  files:
    - test
  requires:
    - cmake
    - ninja
    - vs2017_win-64
about:
  description: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2
    spec.
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp.wiki.git
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1eb0954e-d822-461f-941e-ca377c6e32b1
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/yaml-cpp-feedstock.git
  sha: 18132d58d42899a1745bdc20e2131e2f7cb0352e
