# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_5epydm1y3t\clone\recipe, last modified Mon Jan 23 19:10:01 2023
# ------------------------------------------------

package:
  name: powershell_shortcut_miniconda
  version: 0.0.1
build:
  number: '1'
  string: haa95532_1
requirements:
  build: []
  run:
    - python
  run_constrained:
    - anaconda-navigator >=1.9.8
app:
  entry: start powershell.exe -ExecutionPolicy ByPass -NoExit -Command  "& '{CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1'
    ; conda activate '{CONDA_PREFIX}'"
  summary: Anaconda Powershell Prompt
  type: desk
about:
  license: BSD-3-Clause
  license_family: BSD
  summary: Powershell shortcut creator for Windows (using menuinst)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5e90af51-e48a-41e7-8aa2-a942c87c2a25
  remote_url: git@github.com:AnacondaRecipes/powershell_shortcut_miniconda-feedstock.git
  sha: 2587d187bb381ca3b31dd63057757acfbed35c00
