# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Oct 19 14:29:16 2023
# ------------------------------------------------

package:
  name: archspec
  version: 0.2.1
source:
  sha256: 0974a8a95831d2d43cce906c5b79a35d5fd2bf9be478b0e3b7d83ccc51ac815e
  url: https://pypi.io/packages/source/a/archspec/archspec-0.2.1.tar.gz
build:
  entry_points:
    - archspec = archspec.cli:main
  noarch: python
  number: '0'
  script: /croot/archspec_1697725767277/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.08.22 h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.11 h7f8727e_2
    - pip 23.3 py311h06a4308_0
    - poetry-core 1.5.2 py311h06a4308_0
    - python 3.11.5 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py311h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py311h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.6
test:
  commands:
    - pip check
    - archspec --help
  imports:
    - archspec
    - archspec.cpu
  requires:
    - pip
about:
  description: A library to query system architecture
  dev_url: https://github.com/archspec/archspec/
  doc_url: https://archspec.readthedocs.io/
  home: https://pypi.org/project/archspec/
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: A library to query system architecture
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 702f3f1f-9cfd-4b0d-89a6-511b904b4b15
  recipe-maintainers:
    - anthchirp
    - isuruf
  remote_url: git@github.com:AnacondaRecipes/archspec-feedstock.git
  sha: ef00e13d01bdea823596816c7c937ff2d7a7cac8
