# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_4cwj7szdx5\clone\recipe, last modified Fri Jun 16 17:12:06 2023
# ------------------------------------------------

package:
  name: libssh2
  version: 1.10.0
source:
  sha256: 2d64e90f3ded394b91d3a2e774ca203a4179f69aebee03003e5a6fa621e41d51
  url: https://www.libssh2.org/download/libssh2-1.10.0.tar.gz
build:
  number: '2'
  run_exports:
    - libssh2 >=1.10.0,<2.0a0
  string: he2ea4bf_2
requirements:
  build:
    - cmake-no-system 3.25.3 h6c2663c_0
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.05.30 haa95532_0
    - openssl 3.0.8 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - openssl >=3.0.8,<4.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\\libssh2.h           exit 1
    - if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1
    - if not exist %LIBRARY_INC%\\libssh2_sftp.h      exit 1
    - if not exist %LIBRARY_LIB%\\libssh2.lib         exit 1
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  doc_url: https://www.libssh2.org/docs.html
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4c8eb693-68b1-4e2f-b810-c8ebfc8c2e7d
  recipe-maintainers:
    - shadowwalkersb
  remote_url: git@github.com:AnacondaRecipes/libssh2-feedstock.git
  sha: e811d4215d64e348b7a115c0f035b721d4d8ebbe
