# This file created by conda-build 3.28.1
# meta.yaml template originally from:
# C:\b\abs_e8p75b4m9q\clone\recipe, last modified Tue Dec 12 14:11:52 2023
# ------------------------------------------------

package:
  name: menuinst
  version: 2.0.1
source:
  fn: menuinst-2.0.1.tar.gz
  sha256: 1ccd540ae5d3c348eef3761529a392184057fe9f21ea2dddb09a04b7ad9e9398
  url: https://github.com/conda/menuinst/archive/2.0.1.tar.gz
build:
  missing_dso_whitelist: null
  number: '1'
  script:
    - del /q "C:\b\abs_e8p75b4m9q\croot\menuinst_1702390332729\work\\menuinst\\data\\osx_launcher_*"
    - del /q "C:\b\abs_e8p75b4m9q\croot\menuinst_1702390332729\work\\menuinst\\data\\appkit_launcher_*"
    - C:\\b\\abs_e8p75b4m9q\\croot\\menuinst_1702390332729\\_h_env\\python.exe -m
      pip install . -vv --no-build-isolation --no-deps
    - copy "%SP_DIR%\\menuinst\\_legacy\cwp.py" "%PREFIX%\\"
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.0.1
  skip_compile_pyc:
    - cwp.py
  string: py311hd77b12b_1
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - python 3.11.5 he1021f5_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - packaging 23.1 py311haa95532_0
    - pip 23.3.1 py311haa95532_0
    - python 3.11.5 he1021f5_0
    - setuptools 68.0.0 py311haa95532_0
    - setuptools-scm 7.1.0 py311haa95532_0
    - setuptools_scm 7.1.0 hd3eb1b0_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - typing-extensions 4.7.1 py311haa95532_0
    - typing_extensions 4.7.1 py311haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py311haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - menuinst
    - menuinst._legacy
    - menuinst.api
    - menuinst.platforms.win_utils.winshortcut
  requires:
    - pip
about:
  description: 'This package provides cross platform menu item installation for conda
    packages.


    If a conda package ships a menuinst JSON document under $PREFIX/Menu, conda will
    invoke

    menuinst to process the JSON file and install the menu items in your operating
    system.

    The menu items are removed when the package is uninstalled.

    '
  dev_url: https://github.com/conda/menuinst/
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e81d1541-a80f-48f8-af1d-e005f622b25c
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: git@github.com:AnacondaRecipes/menuinst-feedstock.git
  sha: 695d12f1fde0426466f7310fe33068153bcbd5f8
