# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_88drkd35d4\clone\recipe, last modified Mon Dec  4 19:52:20 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.11.0
source:
  sha256: 74f24daabb4642dcb36a97013fb753bb7ba99c112724b48e2b59d60294012da6
  url: https://github.com/conda/conda/archive/23.11.0.tar.gz
build:
  always_include_files:
    - Scripts/activate
    - Scripts/activate.bat
    - Scripts/deactivate
  number: '0'
  script: C:\\b\\abs_88drkd35d4\\croot\\conda_1701719561256\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv && C:\\b\\abs_88drkd35d4\\croot\\conda_1701719561256\\_h_env\\python.exe
    -m conda init --install
  string: py311haa95532_0
requirements:
  build:
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
  host:
    - brotli-python 1.0.9 py311hd77b12b_7
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - certifi 2023.11.17 py311haa95532_0
    - cffi 1.16.0 py311h2bbff1b_0
    - charset-normalizer 2.0.4 pyhd3eb1b0_0
    - colorama 0.4.6 py311haa95532_0
    - cryptography 41.0.3 py311h89fc84f_0
    - editables 0.3 py311haa95532_0
    - hatch-vcs 0.3.0 py311haa95532_0
    - hatchling 1.18.0 py311haa95532_0
    - idna 3.4 py311haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - menuinst 2.0.0 py311hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - packaging 23.1 py311haa95532_0
    - pathspec 0.10.3 py311haa95532_0
    - pip 23.3.1 py311haa95532_0
    - pluggy 1.0.0 py311haa95532_1
    - pycparser 2.21 pyhd3eb1b0_0
    - pyopenssl 23.2.0 py311haa95532_0
    - pysocks 1.7.1 py311haa95532_0
    - python 3.11.5 he1021f5_0
    - requests 2.31.0 py311haa95532_0
    - ruamel.yaml 0.17.21 py311h2bbff1b_0
    - setuptools 68.0.0 py311haa95532_0
    - setuptools-scm 7.1.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tqdm 4.65.0 py311h746a85d_0
    - trove-classifiers 2023.10.18 py311haa95532_0
    - typing-extensions 4.7.1 py311haa95532_0
    - typing_extensions 4.7.1 py311haa95532_0
    - tzdata 2023c h04d1e81_0
    - urllib3 1.26.18 py311haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py311haa95532_0
    - win_inet_pton 1.1.0 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - archspec
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=23.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - jsonpatch >=1.32
    - menuinst
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.11,<3.12.0a0
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
  run_constrained:
    - conda-build >=3.27
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams: null
  imports:
    - conda
    - conda_env
  requires:
    - m2-base
    - m2-bash
    - m2-filesystem
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 885b1f9e-6812-4df1-8b89-6243ea77494c
  remote_url: git@github.com:AnacondaRecipes/conda-feedstock.git
  sha: dd614fe190d3e24b013ea50c5b945cbe51af1683
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
